ROOT_PATH_DATA = '/home/congdc/project/scheduled-delivery/data/data_test'

#param

COORDINATES_DEPOT = [0,0]

NUM_TRUCK = 2
CAP_TRUCK = 1500
NUM_DRONE =  2
CAP_DRONE = 40
DURATION_DRONE = 30
SPEED_DRONE = 0.6
SPEED_TRUCK = 0.4
WORKING_TIME = 60

POP_SIZE = 6

SIZE_CHOICE = 2
SIZE_CROSSOVER = 2
