"""empty message

Revision ID: 05d29244bf9e
Revises: a7f622d63b96
Create Date: 2022-09-28 10:49:19.964612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d29244bf9e'
down_revision = 'a7f622d63b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_package', sa.Integer(), nullable=True),
    sa.Column('id_target', sa.Integer(), nullable=True),
    sa.Column('time_order', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('package')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_package', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_order', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='package_pkey')
    )
    op.drop_table('order')
    # ### end Alembic commands ###
