"""empty message

Revision ID: 239d102a6d65
Revises: 37ee3b38db3a
Create Date: 2022-09-28 14:43:31.769088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239d102a6d65'
down_revision = '37ee3b38db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('id_root', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_user')
    op.drop_column('order', 'id_root')
    # ### end Alembic commands ###
