"""empty message

Revision ID: 247209e85287
Revises: cfd5b3658550
Create Date: 2022-10-01 16:00:51.822921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247209e85287'
down_revision = 'cfd5b3658550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('limit_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'limit_weight')
    # ### end Alembic commands ###
