"""empty message

Revision ID: 2d0ec186bc0e
Revises: b2bd7e004b55
Create Date: 2022-09-27 21:32:37.971675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0ec186bc0e'
down_revision = 'b2bd7e004b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise', sa.Column('logo_path', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprise', 'logo_path')
    # ### end Alembic commands ###
