"""empty message

Revision ID: 48d3dfcbf237
Revises: 79a52d089d99
Create Date: 2022-09-28 10:55:07.348581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d3dfcbf237'
down_revision = '79a52d089d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('d2ue')
    op.add_column('depot', sa.Column('id_root', sa.Integer(), nullable=True))
    op.add_column('depot', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('depot', 'is_user')
    op.drop_column('depot', 'id_root')
    op.create_table('d2ue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_depot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_root', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='d2ue_pkey')
    )
    # ### end Alembic commands ###
