"""empty message

Revision ID: 5936dc4504ac
Revises: 48d3dfcbf237
Create Date: 2022-09-28 12:06:13.942278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5936dc4504ac'
down_revision = '48d3dfcbf237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depot', sa.Column('address', sa.String(length=120), nullable=True))
    op.drop_column('depot', 'coordinate_y')
    op.drop_column('depot', 'coordinate_x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depot', sa.Column('coordinate_x', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('depot', sa.Column('coordinate_y', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('depot', 'address')
    # ### end Alembic commands ###
