"""empty message

Revision ID: 68fdf2e578a3
Revises: 239d102a6d65
Create Date: 2022-09-28 14:59:38.238370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fdf2e578a3'
down_revision = '239d102a6d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('order', sa.Column('type', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('content', sa.String(length=120), nullable=True))
    op.add_column('order', sa.Column('id_receiver', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('id_sender', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('order', 'id_root')
    op.drop_column('order', 'id_target')
    op.drop_column('order', 'id_package')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('id_package', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('id_target', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('id_root', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order', 'status')
    op.drop_column('order', 'id_sender')
    op.drop_column('order', 'id_receiver')
    op.drop_column('order', 'content')
    op.drop_column('order', 'type')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###
