"""empty message

Revision ID: 76b9ed7f5c63
Revises: aa794acb041f
Create Date: 2022-09-28 10:33:23.018363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b9ed7f5c63'
down_revision = 'aa794acb041f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('d2ue', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.drop_column('d2ue', 'is_enterprise')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('d2ue', sa.Column('is_enterprise', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('d2ue', 'is_user')
    # ### end Alembic commands ###
