"""empty message

Revision ID: 79a52d089d99
Revises: 05d29244bf9e
Create Date: 2022-09-28 10:52:20.555769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a52d089d99'
down_revision = '05d29244bf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('id_root', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_user')
    op.drop_column('customer', 'id_root')
    # ### end Alembic commands ###
