"""empty message

Revision ID: 809a39550442
Revises: 753f1081826c
Create Date: 2022-09-27 12:01:38.258229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809a39550442'
down_revision = '753f1081826c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('id_card', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('dob', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('nationality', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('place_of_origin', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('place_of_recidence', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('date_of_expiry', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('tax_id_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'user', ['id_card'])
    op.create_unique_constraint(None, 'user', ['tax_id_number'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'tax_id_number')
    op.drop_column('user', 'date_of_expiry')
    op.drop_column('user', 'place_of_recidence')
    op.drop_column('user', 'place_of_origin')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'id_card')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
