"""empty message

Revision ID: a7f622d63b96
Revises: 76b9ed7f5c63
Create Date: 2022-09-28 10:46:54.153133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f622d63b96'
down_revision = '76b9ed7f5c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_root', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('is_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_user')
    op.drop_column('product', 'id_root')
    # ### end Alembic commands ###
