"""empty message

Revision ID: aa794acb041f
Revises: dc0083787153
Create Date: 2022-09-28 10:27:46.049472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa794acb041f'
down_revision = 'dc0083787153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d2ue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_depot', sa.Integer(), nullable=True),
    sa.Column('id_root', sa.Integer(), nullable=True),
    sa.Column('is_enterprise', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depot')
    op.drop_table('d2ue')
    # ### end Alembic commands ###
