"""empty message

Revision ID: cfd5b3658550
Revises: 78c692647d04
Create Date: 2022-10-01 15:52:33.046483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd5b3658550'
down_revision = '78c692647d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'money')
    # ### end Alembic commands ###
