"""empty message

Revision ID: d7fad6464158
Revises: fb23964e5d39
Create Date: 2022-10-01 09:19:25.825542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fad6464158'
down_revision = 'fb23964e5d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'notification', ['is_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='unique')
    op.drop_column('notification', 'is_user')
    # ### end Alembic commands ###
