"""empty message

Revision ID: dc0083787153
Revises: 6ae0f8add69c
Create Date: 2022-09-28 02:05:49.552236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0083787153'
down_revision = '6ae0f8add69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.Column('id_sender', sa.Integer(), nullable=True),
    sa.Column('id_receiver', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
